services:
  app:
    build: .
    ports:
    - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER= postgres
      - POSTGRES_PASSWORD= postgres
      - POSTGRES_DB= lemon
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
  redis:
    image: redis:latest    
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data  
volumes:
  pgdata:       
  redisdata: